#!/bin/sh

python -m sqlacodegen --generator sqlmodels --options noconstraints,nocomments,noindexes,nojoined,nobidi postgresql://zufechten:changeme@localhost:5432 > ../../../zufechten-api/src/models/models.py