services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: zufechten
      POSTGRES_PASSWORD: changeme
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zufechten"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
